Added status code check
tbdscripts/cosmo-gmod pull request #1
Opened 2022-01-16 15:53 UTC by stubbo

lets not say success when it fails 🙄

2022-01-16 16:56 UTC, zeo requested changes

2022-01-16 16:56 UTC, zeo commented on lua/cosmo/core/sv_http.lua
> +    if code != 200 then
Success doesn't always imply it's a 200, for example the API returns 204 aswell for the update endpoints

2022-01-16 18:15 UTC, zeo requested changes
This PR would throw several errors.
Line 32, httpFailed will be nil, httpFailed needs to be defined before httpSuccess if you want to use it in httpSuccess. Due to it being a local function

Also `promise` is not passed as a parameter so would throw an error aswell.
Same goes for several other variables (url, reason)

2022-01-16 18:16 UTC, zeo commented on lua/cosmo/core/sv_http.lua
> +    Cosmo.Log.Debug("Endpoint:", url)
`url` is not defined here

2022-01-16 18:16 UTC, zeo commented on lua/cosmo/core/sv_http.lua
> +    promise:Resolve(body, code, headers)
`promise` is not defined here

2022-01-16 18:16 UTC, zeo commented on lua/cosmo/core/sv_http.lua
> +        return httpFailed("Returned invalid response code: " .. code)
httpFailed is nil here

2022-01-16 18:18 UTC, zeo commented
Should be good to merge when these errors are fixed.

2022-01-16 23:48 UTC, Lythium4848 commented
fixed :)

2022-02-20 14:10 UTC, FelixKLG requested changes
add the term penis to overy error message

2022-05-18 11:26 UTC, closed without merging